<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * When a storefront request carries ?preview_theme=... or ?theme=..., every
 * internal /online_store link/form generated by route()/url() (in any theme's
 * Blade files, and in StorefrontPresenter-built product/category URLs) is
 * missing that override, because route() only ever appends query parameters
 * that were explicitly passed to it — Laravel's URL::defaults() only fills in
 * parameters a route's URI actually declares, which none of the storefront
 * routes do for preview_theme/theme.
 *
 * Rather than touching every route() call in every theme (this must work for
 * all storefront themes, not just one), this rewrites the already-rendered
 * HTML response: any href="" / action="" that points at /online_store gets
 * the preserved param appended, merging with whatever query string is
 * already there. It also covers the one other shape used across themes'
 * cart pages — a route() URL passed as a single-quoted JS string literal,
 * e.g. @click="checkout('{{ route('checkout') }}')" — since that URL drives
 * a window.location.href navigation (storefront.js's checkout()) just like
 * a plain anchor would. Only ever runs on the online_store route group, and
 * only ever touches the response when the param is actually present on the
 * incoming request, so persisted store_settings.theme / normal production
 * navigation is completely untouched.
 */
class PreserveStorefrontPreviewTheme
{
    private const PRESERVED_KEYS = ['preview_theme', 'theme'];

    public function handle(Request $request, Closure $next)
    {
        $preserve = array_filter(
            $request->only(self::PRESERVED_KEYS),
            fn ($value) => $value !== null && $value !== ''
        );

        $response = $next($request);

        if (empty($preserve) || $response instanceof JsonResponse || ! method_exists($response, 'getContent')) {
            return $response;
        }

        $contentType = $response->headers->get('Content-Type', '');
        if ($contentType !== '' && ! str_contains($contentType, 'text/html')) {
            return $response;
        }

        $content = $response->getContent();
        if (! is_string($content) || $content === '') {
            return $response;
        }

        $suffix = http_build_query($preserve);

        $appendPreserved = function (string $full, string $prefix, string $path, string $query, string $closer) use ($suffix, $preserve) {
            // Don't double up if a link somehow already carries these keys.
            foreach (array_keys($preserve) as $key) {
                if (str_contains($query, "{$key}=")) {
                    return $full;
                }
            }

            $glue = $query === '' ? '?' : '&';

            return "{$prefix}{$path}{$query}{$glue}{$suffix}{$closer}";
        };

        // href="" / action="" attributes.
        $content = preg_replace_callback(
            '/(href|action)="((?:https?:\/\/[^"\/]+)?\/online_store(?:\/[^"?]*)?)(\?[^"]*)?"/i',
            fn (array $m) => $appendPreserved($m[0], "{$m[1]}=\"", $m[2], $m[3] ?? '', '"'),
            $content
        );

        // Single-quoted URL passed as a JS call argument, e.g. checkout('...').
        $content = preg_replace_callback(
            "/'((?:https?:\\/\\/[^'\\/]+)?\\/online_store(?:\\/[^'?]*)?)(\\?[^']*)?'/i",
            fn (array $m) => $appendPreserved($m[0], "'", $m[1], $m[2] ?? '', "'"),
            $content
        );

        $response->setContent($content);

        return $response;
    }
}
